CREATE TABLE IF NOT EXISTS SAVED_GAMES(
ID int PRIMARY KEY AUTO_INCREMENT,
PLAYER varchar(255) NOT NULL,
FINISHED boolean NOT NULL,
SCORE int NOT NULL,
GAMESTATE varchar(420) NOT NULL);

CREATE TABLE IF NOT EXISTS SCORE_BOARD(
ID int PRIMARY KEY AUTO_INCREMENT,
PLAYER varchar(255) NOT NULL,
SCORE INT NOT NULL
);
